#!/bin/bash
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
PURPLE='\033[0;35m'
Blue="\033[1;36m"
GREEN='\033[0;32m'
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
data_ip="https://aio.tekirovpn.my.id/reseller"
use=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $2}')
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $(date -d "$date_list" +%s) -lt $(date -d "$useexp" +%s) ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          TEKIRO AUTOSCRIPT PREMIUM          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/femashendriyuliadi"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6289699474601"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
Repo1="https://aio.tekirovpn.my.id/"
export MYIP=$( curl -s https://ipinfo.io/ip/ )
SELLER=$(curl -sS ${Repo1}reseller | grep $MYIP | awk '{print $2}')
Exp100=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/rohmatsb-biz/izinkansaya/main/ip"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION
clear
OR='\033[1;93m'
c="\033[0;36m" #biruterang
g="\e[92;1m"
r="\033[1;31m"  #REDTERANG
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
AKTIF="VERIFED"
TOKEN="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"
REPO="https://github.com/rohmatsb-biz/izinkansaya.git"
EMAIL="rohmatsb.biz@gmail.com"
USER="rohmatsb-biz"


add-ip() {
TIMES="10"
CHATID="5932540071"
KEY="6478027776:AAGBRpE2Scyqsf8gHhVPukhREmD4CmaYgEI"
URL="https://api.telegram.org/bot$KEY/sendMessage"


    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone ${REPO} /root/izinkansaya/ &> /dev/null
    clear
    echo -e "MASUKAN IP VPS YANG BELUM DI DAFTAR !"
    echo -e ""
    read -p "Input IP Address : " ip
    CLIENT_EXISTS=$(grep -w $ip /root/izinkansaya/ip | wc -l)
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo "IP Already Exist !"
    exit 0
    fi
    echo -e ""
   # read -p "  Input Username IP (Example : Tekiro) : " name
    name=TZA7nkNkkMbH7eR`</dev/urandom tr -dc A-Z0-9 | head -c4`
    echo -e ""
    clear
    echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "      $PURPLE  Chose Expiry Day ${NC}"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "  ${Blue}  1.)${NC} ☞ 30 Days $NC "
echo -e "  ${Blue}  2.)${NC} ☞ 60 Days $NC "
echo -e "  ${Blue}  3.)${NC} ☞ 90 Days $NC "
echo -e "  ${Blue}  4.)${NC} ☞ Lifetime $NC "
echo -e "  ${Blue}  5.)${NC} ☞ Custom Expired $NC "
echo -e "\e[0m————————————————————————————————————————\e[0m"
    echo -e ""
    read -p "Select Number 1 - 5 : " exp
    
    if [[ ${exp} == '1' ]]; then
    exp2=`date -d "30 days" +"%d-%b-%Y"`
    echo "### ${name} ${exp2} ${ip}" >> /root/izinkansaya/ip
    elif [[ ${exp} == '2' ]]; then
    exp2=`date -d "60 days" +"%d-%b-%Y"`
    echo "### ${name} ${exp2} ${ip}" >> /root/izinkansaya/ip
    elif [[ ${exp} == '3' ]]; then
    exp2=`date -d "90 days" +"%d-%b-%Y"`
    echo "### ${name} ${exp2} ${ip}" >> /root/izinkansaya/ip
    elif [[ ${exp} == '4' ]]; then
    exp2=`date -d "360 days" +"%d-%b-%Y"`
    echo "### ${name} ${exp2} ${ip}" >> /root/izinkansaya/ip
    elif [[ ${exp} == '5' ]]; then
    read -p "Input Expired Days : " exp11
    exp2=`date -d "$exp11 days" +"%d-%b-%Y"`
    echo "### ${name} ${exp2} ${ip}" >> /root/izinkansaya/ip
    fi
    cd /root/izinkansaya
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/rohmatsb-biz/izinkansaya
    git push -f https://${TOKEN}@github.com/rohmatsb-biz/izinkansaya.git &> /dev/null
    rm -rf /root/izinkansaya
    clear
    sleep 1
    echo "  Registering IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
    TEXT="
<code>───────────────────────────</code>
<code>    SUCCES  REGISTERED IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ip</code>
<code>Registered On  : $today</code>
<code>Expired On     : $exp2</code>
<code>───────────────────────────</code>
<code>apt update && apt upgrade -y --fix-missing && update-grub && sleep 2 && apt -y install xxd && apt install -y bzip2 && apt install -y curl && apt install -y zip unzip && apt install -y wget && apt install -y curl && apt install -y vim shc python python2 python3 && apt install socat -y ; apt install openssl -y ; wget https://aio.tekirovpn.my.id/run.sh && chmod +x run.sh && ./run.sh</code>
"   
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "      $PURPLE  SUCCESS REGIST YOUR IP          $NC"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "${NC} ☞ USERNAME   : $name $NC"
echo -e "${NC} ☞ IP ADDRESS : $ip $NC"
echo -e "${NC} ☞ REGISTERED : $today $NC"
echo -e "${NC} ☞ EXPIRED ON : $exp2 $NC"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "${NC}apt update && apt upgrade -y --fix-missing && update-grub && sleep 2 && apt -y install xxd && apt install -y bzip2 && apt install -y curl && apt install -y zip unzip && apt install -y wget && apt install -y curl && apt install -y vim shc python python2 python3 && apt install socat -y ; apt install openssl -y ; wget https://aio.tekirovpn.my.id/run.sh && chmod +x run.sh && ./run.sh $NC"
echo -e "\e[0m————————————————————————————————————————\e[0m"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}

del-ip() {
TIMES="10"
CHATID="5932540071"
KEY="6478027776:AAGBRpE2Scyqsf8gHhVPukhREmD4CmaYgEI"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/izinkansaya
    git clone ${REPO} /root/izinkansaya/ &> /dev/null
    clear
    echo ""
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e "   $PURPLE        DELETE IP VPS SUCCESS           $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    grep -E "^###" "/root/izinkansaya/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    grep -E "^#&"  "/root/izinkansaya/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"

    read -p "Input IP Address To Delete : " ipdel
    name=$(cat /root/izinkansaya/ip | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/izinkansaya/ip | grep $ipdel | awk '{print $3}')
    if [[ ${exp} == 'Lifetime' ]]; then
    sed -i "/^#&   $name   $exp $ipdel/,/^},{/d" /root/izinkansaya/ip
    else
    sed -i "/^### $name $exp $ipdel/,/^},{/d" /root/izinkansaya/ip
    fi
    cd /root/izinkansaya
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/rohmatsb-biz/izinkansaya
    git push -f https://${TOKEN}@github.com/rohmatsb-biz/izinkansaya.git &> /dev/null
    rm -rf /root/izinkansaya
    clear
    sleep 1
    echo "  Delete IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT1="
<code>───────────────────────────</code>
<code>    SUCCES DELETE  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp</code>
<code>───────────────────────────</code>
"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo -e "   $PURPLE        DELETE IP VPS SUCCESS           $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e " ${NC} ☞ USERNAME   :$PURPLE $name $NC"
echo -e " ${NC} ☞ IP ADDRESS :$PURPLE $ipdel $NC"
echo -e " ${NC} ☞ EXPIRED ON :$PURPLE $exp $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
}

renew-ip() {
TIMES="10"
CHATID="5932540071"
KEY="6478027776:AAGBRpE2Scyqsf8gHhVPukhREmD4CmaYgEI"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/izinkansaya
    git clone ${REPO} /root/izinkansaya/ &> /dev/null
    clear
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo -e "${OR}│${NC}${g}  .::.${NC} RENEW IP VPS ${NC}${g}.::. $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    grep -E "^###" "/root/izinkansaya/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo ""
    read -p "  Input IP Address To Renew : " ipdel
    read -p "  Input Days  : " days
    name=$(cat /root/izinkansaya/ip | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/izinkansaya/ip | grep $ipdel | awk '{print $3}')
    now=$(date +%d-%b-%Y)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $days))
    exp4=`date -d "$exp3 days" +"%d-%b-%Y"`
    sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/g" /root/izinkansaya/ip
    cd /root/izinkansaya
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/rohmatsb-biz/izinkansaya
    git push -f https://${TOKEN}@github.com/rohmatsb-biz/izinkansaya.git &> /dev/null
    rm -rf /root/izinkansaya
    clear
    sleep 1
    echo "  Renew IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT2="
<code>───────────────────────────</code>
<code>    SUCCES RENEW  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
    echo ""
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo -e "   $PURPLE        RENEW IP VPS SUCCESS           $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e " ${NC} ☞ USERNAME   :$PURPLE $name $NC"
echo -e " ${NC} ☞ IP ADDRESS :$PURPLE $ipdel $NC"
echo -e " ${NC} ☞ EXPIRED ON :$PURPLE $exp4 $NC"
    echo -e "\e[0m      ————————————————————————————————————————\e[0m"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}

clear

echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e "   $PURPLE             MENU RESELLER IP           $NC"
echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e "   $PURPLE    NAMA RESELLER IP :$NC $SELLER"
echo -e "   $PURPLE    LICENSE RESELLER IP :$NC $AKTIF"
echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo -e "  ${Blue}    1.)${NC} ☞ REGIST IP $NC"
echo -e "  ${Blue}    2.)${NC} ☞ DELETE IP $NC"
echo -e "  ${Blue}    3.)${NC} ☞ RENEW IP $NC"
echo -e "\e[0m      ————————————————————————————————————————\e[0m"
echo ""
read -p " Select From Options : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
del-ip
;;
3 | 03)
clear
renew-ip
;;
4 | 04)
menu
;;
*)
exit
;;
esac