#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\e[0m'
rd='\e[36m' #cyan
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
xl='\e[91m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://raw.githubusercontent.com/salamsatuu/nyali/"
BOT="https://raw.githubusercontent.com/salamsatuu/nyali/"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
data_ip="https://raw.githubusercontent.com/rohmatsb-biz/rohshop-tkr/main/reseller"
use=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $2}')
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $(date -d "$date_list" +%s) -lt $(date -d "$useexp" +%s) ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          TEKIRO AUTOSCRIPT PREMIUM          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/femashendriyuliadi"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6289699474601"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
echo -e "\033[1;36m┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "   \e[1;97;101m       ADD BOT NOTIF VIA TELE         \e[0m"
echo -e "\033[1;36m└━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m"
echo -e "  ${xl}[1]${NC}${rd} Add Bot Notifikasi${NC}"
echo -e "  ${xl}[2]${NC}${rd} Delete Bot Notifikasi${NC}"
echo -e "  ${xl}[3]${NC}${rd} Install Bot Telegram${NC}"
echo -e "  ${xl}[4]${NC}${rd} Add Admin Bot${NC}"
echo -e ""
echo -e "  ${xl}[0]${NC}${rd} Back To Menu${NC}"
echo -e ""
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "  Select From Options [ 1 - 4 or 0 ] : " menu
case $menu in
1) clear ;
    add-bot-notif
    ;;
2) clear ;
    del-bot-notif
    ;;
3) clear ;
    add-bot-panel
    ;;
4) clear ;
    add_bot
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
