#!/bin/bash
# =========================================
# Menu For Script
# Edition : Stable Edition V2.0
# Auther  : TekiroVpn X LynzVpn X ProfAmpoh
# (C) Copyright 2023-2024
# =========================================
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
        echo -e "       Delete Vmess Account       "
        echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
		echo ""
		echo "You have no existing clients!"
		echo ""
		echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
		read -n 1 -s -r -p "Press any key to back on menu"
        menu
	fi

	clear
	echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
    echo -e "       Delete Vmess Account       "
    echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
    echo "  User       Expired  " 
	echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
	grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
    echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
	read -rp "Input Username : " user
    if [ -z $user ]; then
    menu
    else
    exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^### $user $exp/,/^},{/d" /etc/vmess/.vmess.db
    rm -rf /etc/vmess/$user
    rm -rf /etc/lynz/limit/vmess/ip
    systemctl restart xray > /dev/null 2>&1
    clear
    echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
    echo " Vmess Account Deleted Successfully"
    echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
    echo " Client Name : $user"
    echo " Expired On  : $exp"
    echo -e "\e[0m   ———————————————————————————————————————————————\e[0m"
    echo ""
    fi
    echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
m-vmess