#!/bin/bash
# =========================================
# Menu For Script
# Edition : Stable Edition V2.0
# Auther  : TekiroVpn X LynzVpn X ProfAmpoh
# (C) Copyright 2023-2024
# =========================================
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="レスキセティワン"
export KEY="レスキセティワン"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
data_ip="https://raw.githubusercontent.com/rohmatsb-biz/izinkansaya/main/ip"
use=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $2}')
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $(date -d "$date_list" +%s) -lt $(date -d "$useexp" +%s) ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          TEKIRO AUTOSCRIPT PREMIUM          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/femashendriyuliadi"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6289699474601"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
#Domain
domain=$(cat /etc/xray/domain)

echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "   $PURPLE        SSH          $NC"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e ""
echo -e "  ${NC} 1.) Create Accounts  $NC"
echo -e "  ${NC} 2.) Trial Accounts  $NC"
echo -e "  ${NC} 3.) Renew Accounts  $NC"
echo -e "  ${NC} 4.) Check User Login $NC"
echo -e "  ${NC} 5.) List Member $NC"
echo -e "  ${NC} 6.) Delete Accounts $NC"
echo -e "  ${NC} 7.) Delete User Expired $NC"
echo -e "  ${NC} 8.) Setup Auto Kill $NC"
echo -e "  ${NC} 9.) Check User Multi Login$NC"
echo -e "  ${NC} 10.) Detail Accounts $NC"
echo -e "  ${NC} 11.) Exit $NC"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "\e[0m————————————————————————————————————————\e[0m"
read -p "Select From Options [ 1 - 10 ] : " menu
echo -e ""
case $menu in
1)
    addssh
    ;;
2)
    trial
    ;;
3)
    renewssh
    ;;
4)
    cekssh
    ;;
5)
    member
    ;;
6)
    delssh
    ;;
7)
    delexp
    ;;
8)
    autokill
    ;;
9)
    ceklim
    ;;
10)
    user-ssh
    ;;
*)
    menu
    ;;
esac
