#!/bin/bash
NC='\e[0m'
DEFBOLD='\e[39;1m'
RB='\e[31;1m'
GB='\e[32;1m'
YB='\e[33;1m'
BB='\e[34;1m'
MB='\e[35;1m'
CB='\e[35;1m'
WB='\e[37;1m'
z="\033[1;93m"
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
clear
echo -e "${z}───────────────────\033[0m"
echo -e "${YB}You have no existing clients!${NC}"
echo -e "${z}───────────────────\033[0m"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-trojan
fi
clear
echo -e "${z}───────────────────\033[0m"
echo -e " ${WB}User Trojan Account${NC}                 "
echo -e "${z}───────────────────\033[0m"
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
echo ""
echo -e "${RB}tap enter to go back${NC}"
echo -e "${z}───────────────────\033[0m"
read -rp "Input Username : " user
if [ -z $user ]; then
m-trojan
else
clear
echo -e "`cat "/etc/user/trojan/$user.txt"`"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-trojan
fi
