#!/bin/bash
# =========================================
# Menu For Script
# Edition : Stable Edition V2.0
# Auther  : TekiroVpn X LynzVpn X ProfAmpoh
# (C) Copyright 2023-2024
# =========================================
clear

PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
CITY=$(cat /etc/xray/city)
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^#& " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo -e "\e[0m————————————————————————————————————————\e[0m"
    echo -e " \e[1;97;101m                CONFIG VLESS ACCOUNT                   \e[0m"
    echo -e "\e[0m————————————————————————————————————————\e[0m"
    echo ""
    echo "You have no existing clients!"
    echo ""
    echo -e "\e[0m————————————————————————————————————————\e[0m"
    read -n 1 -s -r -p "Press [ Enter ] to back on menu vless"
    vless
fi

  echo -e "\e[0m————————————————————————————————————————\e[0m"
  echo -e "  \e[1;97;101m        CONFIG VLESS ACCOUNT         \E[0m"
  echo -e "\e[0m————————————————————————————————————————\e[0m"
        echo "     No  Expired   User"
        grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
user=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
domain=$(cat /etc/xray/domain)
iplim=$(cat /etc/lynz/limit/vless/ip/$user)
Quota=$(cat /etc/vless/$user)
uuid=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
Quota=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 5 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`
cat >/var/www/html/vless-$user.txt <<-END

————————————————————————————————————————
  T E K I R O   P R O J E C T 
————————————————————————————————————————
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

————————————————————————————————————————
Link Akun Vless 
————————————————————————————————————————
Link TLS      : 
${vlesslink1}
————————————————————————————————————————
Link none TLS : 
${vlesslink2}
————————————————————————————————————————
Link GRPC     : 
${vlesslink3}
————————————————————————————————————————
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
clear
echo -e ""
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "  $PURPLE Detail Vless Account          "
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "Remarks       : ${user}"
echo -e "Domain         : ${domain}"
echo -e "ISP            : $ISP"
echo -e "Region         : $CITY"
echo -e "Port TLS       : 443, 8443, 2083, 2053"
echo -e "Port NTLS    : 80, 8880, 8080, 2082"
echo -e "Port gRPC   : 443"
echo -e "id   : ${uuid}"
echo -e "Encryption     : none"
echo -e "Network        : ws"
echo -e "Path           : /vless"
echo -e "Service Name   : vless-grpc"
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "Link TLS       : ${vlesslink1}"
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "Link none TLS  : ${vlesslink2}"
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "Link GRPC      : ${vlesslink2}"
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "Expired On : $expe" 
echo -e "\e[0m━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
m-vmess