#!/bin/bash
# =========================================
# Menu For Script
# Edition : Stable Edition V2.0
# Auther  : TekiroVpn X LynzVpn X ProfAmpoh
# (C) Copyright 2023-2024
# =========================================
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
IP=$(curl -sS ifconfig.me)
CITY=$(cat /etc/xray/city)
clear
NUMBER_OF_CLIENTS=$(grep -c -E "#ssh# " "/etc/ssh/.ssh.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
  echo -e "\e[0m————————————————————————————————————————\e[0m"
  echo -e " \e[1;97;101m          CONFIG SSH ACCOUNT          \E[0m"
  echo -e "\e[0m————————————————————————————————————————\e[0m"
                echo ""
                echo "You have no existing clients!"
                clear
                exit 1
        fi

  echo -e "\e[0m————————————————————————————————————————\e[0m"
  echo -e "  \e[1;97;101m        CONFIG SSH ACCOUNT         \E[0m"
  echo -e "\e[0m————————————————————————————————————————\e[0m"
        echo "     No  Expired   User"
        grep -E "#ssh# " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
user=$(grep -E "#ssh# " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
domain=$(cat /etc/xray/domain)
Pass=$(grep "$Pass" /etc/ssh/.ssh.db | cut -b 21-56 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "#ssh# " "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`

clear
echo ""
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "              SSH Account         "
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "Host             : $domain"
echo -e "Username         : $Login"
echo -e "Password         : $Pass"
echo -e "\e[0m————————————————————————————————————————\e[0m"
#echo -e "Host Slowdns     : ${NS}"
#echo -e "Pub Key          : ${PUB}"
#echo -e "Location         : $CITY"
echo -e "Port OpenSSH     : 443, 80, 22"
echo -e "Port Dropbear    : 443, 109"
echo -e "Port SSH WS      : 80, 8080, 8081-9999"
echo -e "Port SSH SSL WS  : 443"
echo -e "BadVPN UDP       : 7100, 7300, 7300"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e "Expired On       : $expe" 
echo -e "\e[0m————————————————————————————————————————\e[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws